<?php
return [
    // General
    'dir' => 'rtl',
    'lang_code' => 'ar',
    'app_name' => 'ريتيل برو',
    'kuwait' => 'الكويت',
    'save' => 'حفظ',
    'cancel' => 'إلغاء',
    'delete' => 'حذف',
    'edit' => 'تعديل',
    'add' => 'إضافة',
    'search' => 'بحث',
    'actions' => 'إجراءات',
    'status' => 'الحالة',
    'active' => 'نشط',
    'inactive' => 'غير نشط',
    'yes' => 'نعم',
    'no' => 'لا',
    'all' => 'الكل',
    'none' => 'لا شيء',
    'total' => 'الإجمالي',
    'date' => 'التاريخ',
    'notes' => 'ملاحظات',
    'name' => 'الاسم',
    'email' => 'البريد الإلكتروني',
    'phone' => 'الهاتف',
    'address' => 'العنوان',
    'type' => 'النوع',
    'amount' => 'المبلغ',
    'description' => 'الوصف',
    'close' => 'إغلاق',
    'confirm' => 'تأكيد',
    'loading' => 'جاري التحميل...',
    'no_data' => 'لا توجد بيانات',
    'success' => 'تم بنجاح',
    'error' => 'خطأ',
    'warning' => 'تحذير',
    'export_csv' => 'تصدير CSV',
    'print' => 'طباعة',
    'view' => 'عرض',
    'back' => 'رجوع',
    'created_at' => 'تاريخ الإنشاء',
    'updated_at' => 'تاريخ التحديث',

    // Login
    'sign_in' => 'تسجيل الدخول',
    'email_address' => 'البريد الإلكتروني',
    'password' => 'كلمة المرور',
    'login_subtitle' => 'حقائب، إكسسوارات وملابس — الكويت',
    'invalid_credentials' => 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    'db_error' => 'خطأ في قاعدة البيانات — تحقق من بيانات الاتصال.',
    'demo_credentials' => 'بيانات تجريبية',
    'session_expired' => 'انتهت جلستك. يرجى تسجيل الدخول مرة أخرى.',
    'security_error' => 'خطأ أمني',
    'invalid_csrf' => 'رمز الأمان غير صالح. يرجى تحديث الصفحة والمحاولة مرة أخرى.',
    'forbidden' => 'ممنوع',
    'audit_log' => 'سجل التدقيق',

    // Sidebar Navigation
    'nav_core' => 'الرئيسية',
    'nav_dashboard' => 'لوحة التحكم',
    'nav_pos' => 'نقطة البيع',
    'nav_refunds' => 'المرتجعات',
    'nav_products' => 'المنتجات',
    'nav_categories' => 'التصنيفات والوحدات',
    'nav_inventory' => 'المخزون',
    'nav_people' => 'الأشخاص',
    'nav_customers' => 'العملاء',
    'nav_suppliers' => 'الموردين',
    'nav_finance' => 'المالية',
    'nav_purchases' => 'المشتريات',
    'nav_payments' => 'المدفوعات',
    'nav_expenses' => 'المصروفات',
    'nav_management' => 'الإدارة',
    'nav_branches' => 'الفروع',
    'nav_offers' => 'العروض والخصومات',
    'nav_reports' => 'التقارير',
    'nav_users' => 'المستخدمين والصلاحيات',
    'nav_settings' => 'الإعدادات',
    'logout' => 'تسجيل الخروج',
    'all_branches' => 'جميع الفروع',
    'new_sale' => '+ بيع جديد',

    // Dashboard
    'todays_sales' => 'مبيعات اليوم',
    'monthly_sales' => 'مبيعات الشهر',
    'total_invoices' => 'إجمالي الفواتير',
    'total_customers' => 'إجمالي العملاء',
    'total_products' => 'إجمالي المنتجات',
    'low_stock_items' => 'منتجات منخفضة المخزون',
    'needs_reorder' => 'يحتاج إعادة طلب',
    'weekly_sales' => 'المبيعات الأسبوعية',
    'full_report' => 'التقرير الكامل',
    'recent_sales' => 'أحدث المبيعات',
    'view_all' => 'عرض الكل',
    'top_products' => 'أفضل المنتجات',
    'customer' => 'العميل',
    'walk_in' => 'زائر',
    'paid' => 'مدفوع',
    'unpaid' => 'غير مدفوع',
    'partial' => 'جزئي',
    'refunded' => 'مسترجع',
    'units_sold' => 'وحدة مباعة',
    'revenue' => 'الإيرادات',

    // POS
    'search_products' => 'ابحث عن منتج...',
    'all_categories' => 'جميع التصنيفات',
    'scan_barcode' => 'مسح الباركود...',
    'shopping_cart' => 'سلة التسوق',
    'items' => 'منتجات',
    'add_products_start' => 'أضف منتجات لبدء عملية البيع',
    'subtotal' => 'المجموع الفرعي',
    'offer_applied' => 'تم تطبيق العرض',
    'promo_code' => 'رمز الخصم...',
    'apply' => 'تطبيق',
    'extra_disc' => 'خصم إضافي',
    'payment_mode' => 'طريقة الدفع',
    'cash' => 'نقدي',
    'knet' => 'كي نت',
    'wamd' => 'واد',
    'transfer' => 'تحويل',
    'credit' => 'آجل',
    'hold' => 'تعليق',
    'charge' => 'تحصيل',
    'amount_paid_now' => 'المبلغ المدفوع الآن',
    'remaining_credit' => 'المتبقي سيضاف لحساب العميل',
    'select_customer' => 'اختر عميل',
    'quick_add_customer' => 'إضافة عميل سريع',
    'walk_in_customer' => 'عميل زائر',
    'registered' => 'مسجل',
    'full_name' => 'الاسم الكامل',
    'customer_name' => 'اسم العميل',
    'credit_limit' => 'حد الائتمان',
    'save_select' => 'حفظ واختيار',
    'sale_complete' => 'تمت عملية البيع',
    'invoice' => 'فاتورة',
    'no_phone' => 'بدون هاتف',
    'change' => 'تغيير',
    'customer_selected' => 'تم اختيار العميل',
    'selected' => 'تم الاختيار',
    'in_stock' => 'في المخزون',
    'promo_applied' => 'تم تطبيق العرض',
    'promo_not_found' => 'رمز الخصم غير موجود أو منتهي الصلاحية.',
    'no_match_promo' => 'هذا العرض لا ينطبق على المنتجات في سلتك.',
    'enter_promo' => 'أدخل رمز الخصم.',
    'select_customer_credit' => 'اختر عميل للبيع الآجل.',
    'network_error' => 'خطأ في الشبكة.',
    'sale_failed' => 'فشلت عملية البيع.',

    // Products
    'product_management' => 'إدارة المنتجات',
    'add_product' => 'إضافة منتج',
    'edit_product' => 'تعديل منتج',
    'product_name' => 'اسم المنتج',
    'product_name_ar' => 'اسم المنتج (عربي)',
    'sku' => 'رمز المنتج',
    'barcode' => 'الباركود',
    'category' => 'التصنيف',
    'brand' => 'الماركة',
    'cost_price' => 'سعر التكلفة',
    'retail_price' => 'سعر التجزئة',
    'wholesale_price' => 'سعر الجملة',
    'color' => 'اللون',
    'size' => 'المقاس',
    'initial_stock' => 'المخزون الأولي (جميع الفروع)',
    'unit' => 'الوحدة',
    'product_added' => 'تمت إضافة المنتج',
    'product_updated' => 'تم تحديث المنتج',
    'product_deleted' => 'تم حذف المنتج',
    'save_product' => 'حفظ المنتج',
    'print_barcode' => 'طباعة الباركود',
    'stock' => 'المخزون',
    'price' => 'السعر',

    // Categories
    'category_management' => 'التصنيفات والوحدات',
    'add_category' => 'إضافة تصنيف',
    'edit_category' => 'تعديل تصنيف',
    'category_name' => 'اسم التصنيف',
    'category_name_ar' => 'اسم التصنيف (عربي)',
    'parent_category' => 'التصنيف الرئيسي',
    'no_parent' => 'بدون تصنيف رئيسي',
    'emoji' => 'رمز تعبيري',
    'save_category' => 'حفظ التصنيف',
    'category_added' => 'تمت إضافة التصنيف',
    'category_updated' => 'تم تحديث التصنيف',
    'category_deleted' => 'تم حذف التصنيف',
    'units' => 'الوحدات',
    'add_unit' => 'إضافة وحدة',
    'unit_name' => 'اسم الوحدة',
    'unit_symbol' => 'الرمز',
    'unit_added' => 'تمت إضافة الوحدة',
    'unit_deleted' => 'تم حذف الوحدة',
    'products_count' => 'المنتجات',

    // Customers
    'customer_management' => 'إدارة العملاء',
    'add_customer' => 'إضافة عميل',
    'edit_customer' => 'تعديل عميل',
    'customer_name_ar' => 'الاسم (عربي)',
    'customer_type' => 'نوع العميل',
    'retail' => 'تجزئة',
    'wholesale' => 'جملة',
    'address_ar' => 'العنوان (عربي)',
    'save_customer' => 'حفظ العميل',
    'customer_added' => 'تمت إضافة العميل',
    'customer_updated' => 'تم تحديث العميل',
    'customer_deleted' => 'تم حذف العميل',
    'balance' => 'الرصيد',
    'invoices' => 'الفواتير',
    'no_customers' => 'لا يوجد عملاء',

    // Suppliers
    'supplier_management' => 'إدارة الموردين',
    'add_supplier' => 'إضافة مورد',
    'edit_supplier' => 'تعديل مورد',
    'company' => 'الشركة',
    'company_ar' => 'الشركة (عربي)',
    'contact_name' => 'اسم جهة الاتصال',
    'contact_name_ar' => 'اسم جهة الاتصال (عربي)',
    'address_ar_label' => 'العنوان (عربي)',
    'payment_terms' => 'شروط الدفع',
    'save_supplier' => 'حفظ المورد',
    'supplier_added' => 'تمت إضافة المورد',
    'supplier_updated' => 'تم تحديث المورد',
    'supplier_deleted' => 'تم حذف المورد',

    // Purchases
    'purchase_orders' => 'أوامر الشراء',
    'create_po' => 'إنشاء أمر شراء',
    'edit_po' => 'تعديل أمر الشراء',
    'po_number' => 'رقم أمر الشراء',
    'supplier' => 'المورد',
    'branch' => 'الفرع',
    'total_amount' => 'المبلغ الإجمالي',
    'paid_amount' => 'المبلغ المدفوع',
    'pending' => 'معلق',
    'completed' => 'مكتمل',
    'cancelled' => 'ملغي',
    'po_created' => 'تم إنشاء أمر الشراء',

    // Payments
    'payments_dues' => 'المدفوعات والمستحقات',
    'record_payment' => 'تسجيل دفعة',
    'payment_mode_label' => 'طريقة الدفع',
    'customer_dues' => 'مستحقات العملاء',
    'supplier_dues' => 'مستحقات الموردين',
    'payment_history' => 'سجل المدفوعات',
    'due_amount' => 'المبلغ المستحق',
    'pay_now' => 'ادفع الآن',
    'payment_recorded' => 'تم تسجيل الدفعة',

    // Expenses
    'expense_tracker' => 'تتبع المصروفات',
    'add_expense' => 'إضافة مصروف',
    'expense_category' => 'التصنيف',
    'expense_amount' => 'المبلغ',
    'receipt_ref' => 'مرجع الإيصال',
    'expense_recorded' => 'تم تسجيل المصروف',
    'this_month' => 'هذا الشهر',
    'today' => 'اليوم',

    // Inventory
    'inventory_management' => 'المخزون',
    'stock_levels' => 'مستويات المخزون',
    'adjust_stock' => 'تعديل المخزون',
    'stock_in' => 'إدخال مخزون',
    'stock_out' => 'إخراج مخزون',
    'current_qty' => 'الكمية الحالية',
    'new_qty' => 'الكمية الجديدة',
    'reason' => 'السبب',
    'stock_adjusted' => 'تم تعديل المخزون',

    // Reports
    'sales_reports' => 'تقارير المبيعات',
    'period' => 'الفترة',
    'from_date' => 'من',
    'to_date' => 'إلى',
    'generate' => 'إنشاء',
    'daily_breakdown' => 'تفصيل يومي',
    'payment_summary' => 'ملخص المدفوعات',
    'top_selling' => 'المنتجات الأكثر مبيعاً',

    // Offers
    'offers_promos' => 'العروض والخصومات',
    'add_offer' => 'إضافة عرض',
    'offer_title' => 'عنوان العرض',
    'discount_type' => 'نوع الخصم',
    'discount_value' => 'قيمة الخصم',
    'percentage_discount' => 'خصم نسبة مئوية',
    'buy1_get1' => 'اشترِ 1 واحصل على 1',
    'fixed_amount_off' => 'خصم مبلغ ثابت',
    'start_date' => 'تاريخ البداية',
    'end_date' => 'تاريخ النهاية',
    'usage_limit' => 'حد الاستخدام',
    'applies_to' => 'ينطبق على',
    'all_products' => 'جميع المنتجات',
    'offer_created' => 'تم إنشاء العرض',

    // Branches
    'branch_management' => 'الفروع',
    'add_branch' => 'إضافة فرع',
    'branch_name' => 'اسم الفرع',
    'branch_added' => 'تمت إضافة الفرع',

    // Users
    'user_management' => 'المستخدمين والصلاحيات',
    'add_user' => 'إضافة مستخدم',
    'edit_user' => 'تعديل مستخدم',
    'user_name' => 'الاسم',
    'role' => 'الصلاحية',
    'admin' => 'مدير',
    'cashier' => 'كاشير',
    'manager' => 'مشرف',
    'last_login' => 'آخر دخول',
    'user_added' => 'تمت إضافة المستخدم',
    'user_updated' => 'تم تحديث المستخدم',

    // Settings
    'settings' => 'الإعدادات',
    'company_tab' => 'الشركة',
    'invoice_tab' => 'الفاتورة',
    'company_name' => 'اسم الشركة',
    'company_phone' => 'الهاتف',
    'company_address' => 'العنوان',
    'default_currency' => 'العملة الافتراضية',
    'company_logo' => 'شعار الشركة',
    'upload_logo' => 'رفع الشعار',
    'current_logo' => 'الشعار الحالي',
    'delete_logo' => 'حذف الشعار',
    'invoice_prefix' => 'بادئة الفاتورة',
    'invoice_footer' => 'تذييل الفاتورة',
    'vat_number' => 'الرقم الضريبي',
    'show_logo_invoice' => 'عرض شعار الشركة في الفاتورة',
    'save_settings' => 'حفظ الإعدادات',
    'settings_saved' => 'تم حفظ الإعدادات',

    // Invoice
    'invoice_page' => 'فاتورة',
    'bill_to' => 'فاتورة إلى',
    'invoice_number' => 'رقم الفاتورة',
    'invoice_date' => 'تاريخ الفاتورة',
    'payment_status' => 'حالة الدفع',
    'product' => 'المنتج',
    'qty' => 'الكمية',
    'unit_price' => 'سعر الوحدة',
    'discount' => 'الخصم',
    'vat' => 'الضريبة',
    'balance_due' => 'الرصيد المتبقي',
    'thank_you' => 'شكراً لتسوقكم مع ريتيل برو.',
    'returns_policy' => 'يُسمح بإرجاع البضائع خلال 7 أيام مع الإيصال.',

    // Refunds
    'returns_refunds' => 'المرتجعات والاسترداد',
    'search_invoice' => 'ابحث برقم الفاتورة...',
    'find_invoice' => 'بحث عن فاتورة',
    'refund_reason' => 'السبب',
    'refund_to' => 'استرداد إلى',
    'store_credit' => 'رصيد المتجر',
    'customer_return' => 'إرجاع من العميل',
    'defective_product' => 'منتج معيب',
    'wrong_item' => 'منتج خاطئ',
    'size_exchange' => 'تبديل مقاس',
    'other' => 'أخرى',
    'refund_total' => 'الاسترداد',
    'process_refund' => 'معالجة الاسترداد',
    'recent_refunds' => 'آخر المرتجعات',
    'refund_processed' => 'تم الاسترداد',
    'select_items_return' => 'اختر المنتجات للإرجاع.',
    'qty_return' => 'كمية الإرجاع',

    // Language
    'language' => 'اللغة',
    'english' => 'English',
    'arabic' => 'العربية',
    'switch_language' => 'تبديل اللغة',

    // Dashboard Extra
    'monthly_revenue' => 'إيرادات الشهر',
    'pending_dues' => 'مستحقات معلقة',
    'supplier_dues' => 'مستحقات الموردين',
    'customer_receivables' => 'ذمم العملاء',
    'payables_outstanding' => 'مدفوعات مستحقة',
    'active_skus' => 'منتجات نشطة',
    'orders_today' => 'طلبات اليوم',
    'invoices_issued' => 'فواتير صادرة',
    'active_customers' => 'عملاء نشطين',
    'registered_accounts' => 'حسابات مسجلة',
    'branch_performance' => 'أداء الفروع',
    'todays_revenue' => 'إيرادات اليوم',
    'all_branches_combined' => 'جميع الفروع مجتمعة',
    'unpaid_invoices' => 'فواتير غير مدفوعة',
    'credit_invoices' => 'فواتير آجلة',
    'partial_invoices' => 'فواتير جزئية',
    'total_outstanding' => 'إجمالي المستحقات',
    'best_selling' => 'أفضل المنتجات مبيعاً (30 يوم)',
    'due_customers' => 'عملاء مدينين',
    'due_balance' => 'رصيد مستحق',
    'no_outstanding_dues' => 'لا توجد مستحقات',
    'low_stock_alerts' => 'تنبيهات المخزون المنخفض',
    'units_left' => 'وحدة متبقية',
    'reorder' => 'إعادة طلب',
    'all_stock_healthy' => 'جميع مستويات المخزون طبيعية',
    'no_sales_data' => 'لا توجد بيانات مبيعات',
    'orders' => 'طلبات',
    'this_month_label' => 'هذا الشهر',

    // Inventory Extra
    'all_stock' => 'كل المخزون',
    'low_stock' => 'مخزون منخفض',
    'out_of_stock' => 'نفد المخزون',
    'branch_filter' => 'جميع الفروع',
    'quantity' => 'الكمية',
    'last_updated' => 'آخر تحديث',
    'adjust' => 'تعديل',
    'adjustment_type' => 'نوع التعديل',
    'add_stock' => 'إضافة مخزون',
    'remove_stock' => 'سحب مخزون',
    'set_stock' => 'تعيين المخزون',
    'new_quantity' => 'الكمية الجديدة',
    'save_adjustment' => 'حفظ التعديل',

    // Reports Extra
    'sales_report' => 'تقرير المبيعات',
    'filter' => 'تصفية',
    'all_statuses' => 'كل الحالات',
    'summary' => 'ملخص',
    'total_sales' => 'إجمالي المبيعات',
    'total_discount' => 'إجمالي الخصم',
    'avg_order' => 'متوسط الطلب',
    'invoice_list' => 'قائمة الفواتير',
    'mode' => 'الطريقة',

    // Branches Extra
    'location' => 'الموقع',
    'is_active' => 'نشط',

    // Users Extra
    'change_password' => 'تغيير كلمة المرور',
    'new_password' => 'كلمة مرور جديدة',
    'leave_blank' => 'اترك فارغاً للإبقاء على الحالية',

    // Settings Extra
    'tax_tab' => 'الضريبة',
    'vat_enabled' => 'الضريبة مفعلة',
    'vat_rate' => 'نسبة الضريبة (%)',

    // Common table/form
    'created_by' => 'أنشأه',
    'no_records' => 'لا توجد سجلات',
    'are_you_sure' => 'هل أنت متأكد؟',
    'confirm_delete' => 'لا يمكن التراجع عن هذا الإجراء.',
    'per_page' => 'لكل صفحة',
    'showing' => 'عرض',
    'of' => 'من',
    'previous' => 'السابق',
    'next' => 'التالي',

    // POS Extra
    'scan_barcode' => 'امسح الباركود أو اكتب رمز المنتج واضغط Enter...',
    'shopping_cart' => 'البيع الحالي',
    'items' => 'عناصر',
    'walk_in' => 'زبون عابر',
    'walk_in_customer' => 'زبون عابر',
    'select_customer' => 'عميل محفوظ',
    'add_products_start' => 'أضف منتجات لبدء البيع',
    'subtotal' => 'المجموع الفرعي',
    'offer_applied' => 'عرض مطبق',
    'promo_code' => 'رمز العرض...',
    'apply' => 'تطبيق',
    'extra_disc' => 'خصم إضافي',
    'payment_mode' => 'طريقة الدفع',
    'cash' => 'نقداً',
    'knet' => 'كي نت',
    'wamd' => 'ومد',
    'transfer' => 'تحويل',
    'partial' => 'جزئي',
    'credit' => 'آجل',
    'amount_paid_now' => 'المبلغ المدفوع الآن',
    'remaining_credit' => 'المتبقي سيضاف لرصيد العميل',
    'hold' => 'تعليق',
    'resume' => 'استئناف',
    'held_sales' => 'المبيعات المعلقة',
    'no_held_sales' => 'لا توجد مبيعات معلقة.',
    'hold_resumed' => 'تم استئناف البيع المعلق.',
    'charge' => 'دفع',
    'quick_add_customer' => 'إضافة عميل سريع',
    'full_name' => 'الاسم الكامل',
    'customer_name' => 'اسم العميل',
    'retail' => 'تجزئة',
    'wholesale' => 'جملة',
    'credit_limit' => 'حد الائتمان',
    'save_select' => 'حفظ واختيار',
    'no_phone' => 'لا يوجد هاتف',
    'change' => 'تغيير',
    'customer_selected' => 'تم اختيار العميل',
    'selected' => 'تم الاختيار',
    'in_stock' => 'متوفر',
    'no_customers' => 'لا يوجد عملاء',
    'promo_applied' => 'تم تطبيق العرض',
    'promo_not_found' => 'رمز العرض غير موجود أو منتهي.',
    'no_match_promo' => 'هذا العرض لا ينطبق على المنتجات في سلتك.',
    'enter_promo' => 'أدخل رمز العرض.',
    'select_customer_credit' => 'اختر عميلاً للبيع الآجل/الجزئي.',
    'network_error' => 'خطأ في الشبكة.',
    'sale_failed' => 'فشل البيع.',
    'sale_complete' => 'تم البيع',
    'invoice' => 'فاتورة',
    'customer_added' => 'تمت إضافة العميل',

    // Product Extra
    'product_management' => 'إدارة المنتجات',
    'search_products' => 'بحث عن المنتجات...',
    'all_categories' => 'جميع الفئات',
    'add_product' => 'إضافة منتج',
    'edit_product' => 'تعديل المنتج',
    'save_product' => 'حفظ المنتج',
    'product_name' => 'اسم المنتج',
    'product_name_ar' => 'اسم المنتج (العربية)',
    'barcode' => 'باركود',
    'brand' => 'العلامة التجارية',
    'cost_price' => 'سعر التكلفة',
    'retail_price' => 'سعر التجزئة',
    'wholesale_price' => 'سعر الجملة',
    'color' => 'اللون',
    'size' => 'المقاس',
    'initial_stock' => 'المخزون الأولي',
    'unit' => 'الوحدة',
    'product' => 'المنتج',
    'sku' => 'رمز المنتج',
    'category' => 'الفئة',
    'stock' => 'المخزون',
    'qty' => 'الكمية',
    'revenue' => 'الإيرادات',
    'view_all' => 'عرض الكل',
    'full_report' => 'التقرير الكامل',

    // Category Extra
    'category_management' => 'الفئات والوحدات',
    'units' => 'الوحدات',
    'total_categories' => 'إجمالي الفئات',
    'parent_categories' => 'الفئات الرئيسية',
    'sub_categories' => 'الفئات الفرعية',
    'add_category' => 'إضافة فئة',
    'edit_category' => 'تعديل الفئة',
    'category_name' => 'اسم الفئة',
    'category_name_ar' => 'اسم الفئة (العربية)',
    'parent_category' => 'الفئة الرئيسية',
    'parent' => 'الرئيسية',
    'emoji' => 'رمز',
    'total_units' => 'إجمالي الوحدات',
    'in_use' => 'قيد الاستخدام',
    'add_unit' => 'إضافة وحدة',
    'edit_unit' => 'تعديل الوحدة',
    'unit_name' => 'اسم الوحدة',
    'abbreviation' => 'الاختصار',

    // Dashboard extra
    'todays_sales' => 'مبيعات اليوم',
    'total_products' => 'إجمالي المنتجات',
    'low_stock_items' => 'منتجات مخزون منخفض',
    'needs_reorder' => 'يحتاج إعادة طلب',
    'weekly_sales' => 'المبيعات الأسبوعية',

    // Customers Extra
    'customer_management' => 'إدارة العملاء',

    // Suppliers Extra
    'supplier_management' => 'إدارة الموردين',

    // Purchase Orders Extra
    'purchase_orders' => 'أوامر الشراء',

    // Payments Extra
    'payments_dues' => 'المدفوعات والمستحقات',

    // Expenses Extra
    'expense_tracker' => 'تتبع المصروفات',

    // Refunds Extra
    'returns_refunds' => 'المرتجعات والاسترداد',

    // Offers Extra
    'offers_promos' => 'العروض والترويج',

    // Inventory Extra
    'inventory_management' => 'إدارة المخزون',

    // Branches Extra
    'branch_management' => 'إدارة الفروع',

    // Users Extra
    'user_management' => 'المستخدمون والأدوار',

    // Customer/Supplier status
    'balance' => 'الرصيد',
    'last_purchase' => 'آخر شراء',
    'owing' => 'مدين',
    'advance' => 'دفعة مقدمة',
    'clear' => 'مسدد',
    'paid_this_month' => 'المدفوع هذا الشهر',
    'pending_orders' => 'طلبات معلقة',
    'company' => 'الشركة',
    'contact' => 'جهة الاتصال',
    'payment_terms' => 'شروط الدفع',
    'arabic' => 'العربية',
    'available_in_branches' => 'متوفر في',
    'other_branches_available' => 'متوفر في فروع أخرى',
    'out_of_stock' => 'نفد المخزون',
    'pending' => 'معلق',
    'completed' => 'مكتمل',
    'paid' => 'مدفوع',
    'select' => 'اختيار',
    'cancelled' => 'ملغي',
    'payment_history' => 'سجل المدفوعات',
    'received_today' => 'المستلم اليوم',
    'pending_collection' => 'تحصيل معلق',
    'paid_to_suppliers' => 'مدفوع للموردين',
    'overdue_customers' => 'عملاء متأخرون',
    'overdue_suppliers' => 'موردون متأخرون',
    'collect' => 'تحصيل',
    'pay_now' => 'ادفع الآن',
    'record_payment' => 'تسجيل دفعة',

    // Refunds
    'find_invoice_refund' => 'البحث عن فاتورة للاسترجاع',
    'enter_invoice_number' => 'أدخل رقم الفاتورة',
    'qty_return' => 'الكمية المرتجعة',
    'reason' => 'السبب',
    'refund_to' => 'استرجاع إلى',
    'credit' => 'رصيد المتجر',
    'process_refund' => 'معالجة الاسترجاع',
    'recent_refunds' => 'الاسترجاعات الأخيرة',

    // Offers
    'scheduled' => 'مجدول',
    'expired' => 'منتهي',
    'create_offer' => 'إنشاء عرض',
    'disable' => 'تعطيل',
    'enable' => 'تفعيل',
    'offer_title' => 'عنوان العرض',
    'discount_value' => 'قيمة الخصم',
    'promo_code_label' => 'رمز العرض',
    'applies_to' => 'ينطبق على',
    'start_date' => 'تاريخ البداية',
    'end_date' => 'تاريخ الانتهاء',
    'usage_limit' => 'حد الاستخدام',

    // Inventory
    'stock_in' => 'إدخال مخزون',
    'stock_out' => 'إخراج مخزون',
    'adjust_stock' => 'تعديل المخزون',
    'total_stock' => 'إجمالي المخزون',
    'units_all_branches' => 'وحدات في جميع الفروع',
    'healthy_stock' => 'مخزون جيد',
    'low_stock' => 'مخزون منخفض',
    'damage_events' => 'أحداث التلف',
    'stock_levels' => 'مستويات المخزون',
    'recent_movements' => 'الحركات الأخيرة',
    'reference' => 'المرجع',

    // Branches
    'todays_sales' => 'مبيعات اليوم',
    'orders' => 'الطلبات',
    'full_report' => 'عرض التقرير',
    'manager' => 'المدير',

    // Users
    'user' => 'المستخدم',
    'role' => 'الدور',
    'last_login' => 'آخر دخول',

    // Settings
    'backup' => 'النسخ الاحتياطي',
    'company_settings' => 'إعدادات الشركة',
    'company_logo' => 'شعار الشركة',
    'company_name' => 'اسم الشركة',
    'currency' => 'العملة',
    'invoice_settings' => 'إعدادات الفاتورة',
    'invoice_prefix' => 'بادئة الفاتورة',
    'invoice_footer' => 'تذييل الفاتورة',
    'show_logo_invoice' => 'إظهار الشعار في الفاتورة',
    'database_backup' => 'نسخ احتياطي للقاعدة',

    // Reports
    'sales_reports' => 'تقارير المبيعات',
    'category_breakdown' => 'تفصيل الفئات',
    'daily_trend' => 'الاتجاه اليومي',
    'generate' => 'إنشاء',
    'total_sales' => 'إجمالي المبيعات',
    'gross_profit' => 'الربح الإجمالي',
    'total_invoices' => 'إجمالي الفواتير',
    'avg_ticket' => 'متوسط الفاتورة',
    'units_sold' => 'الوحدات المباعة',
    'revenue' => 'الإيرادات',
    'cost' => 'التكلفة',
    'profit' => 'الربح',
    'margin' => 'الهامش',

    // Common extra
    'this_month' => 'هذا الشهر',
    'today' => 'اليوم',
    'receipt_ref' => 'مرجع الإيصال',

    // ── المحاسبة / البيانات المالية (مضاف) ──
    'financial_statements'  => 'البيانات المالية',
    'income_statement'      => 'قائمة الدخل',
    'balance_sheet'         => 'الميزانية العمومية',
    'cash_flow'             => 'التدفق النقدي',
    'ar_aging'              => 'تقادم الذمم المدينة',
    'monthly_trend'         => 'الاتجاه الشهري',
    'full_year'             => 'السنة كاملة',
    'as_of'                 => 'بتاريخ',
    'gross_sales'           => 'إجمالي المبيعات',
    'discount_given'        => 'الخصومات الممنوحة',
    'net_revenue'           => 'صافي الإيرادات',
    'cost_of_goods'         => 'تكلفة البضاعة المباعة',
    'total_cogs'            => 'إجمالي تكلفة البضاعة',
    'operating_expenses'    => 'المصروفات التشغيلية',
    'net_profit'            => 'صافي الربح',
    'total_expenses'        => 'إجمالي المصروفات',
    'gross_revenue'         => 'إجمالي الإيرادات',
    'assets'                => 'الأصول',
    'current_assets'        => 'الأصول المتداولة',
    'cash_and_bank'         => 'النقد والبنك (صافي)',
    'accounts_receivable'   => 'الذمم المدينة',
    'inventory_value'       => 'قيمة المخزون (بالتكلفة)',
    'total_assets'          => 'إجمالي الأصول',
    'liabilities_equity'    => 'الخصوم وحقوق الملكية',
    'current_liabilities'   => 'الخصوم المتداولة',
    'accounts_payable'      => 'الذمم الدائنة',
    'total_liabilities'     => 'إجمالي الخصوم',
    'equity'                => 'حقوق الملكية',
    'retained_earnings'     => 'الأرباح المحتجزة (إجمالي)',
    'opening_capital'       => 'رأس المال الافتتاحي / أخرى',
    'total_equity'          => 'إجمالي حقوق الملكية',
    'total_liab_equity'     => 'إجمالي الخصوم + حقوق الملكية',
    'cumulative_all_time'   => '(تراكمي — كل الفترات)',
    'cash_inflow'           => 'التدفقات النقدية الداخلة',
    'cash_outflow'          => 'التدفقات النقدية الخارجة',
    'net_cash_flow'         => 'صافي التدفق النقدي',
    'operating_activities'  => 'الأنشطة التشغيلية',
    'cash_sales_direct'     => 'مبيعات نقدية (نقد / بطاقة / تحويل)',
    'credit_collected'      => 'تحصيلات الفواتير الآجلة',
    'credit_collections'    => 'التحصيل الآجل',
    'direct_sales'          => 'مبيعات مباشرة',
    'total_inflows'         => 'إجمالي التدفقات الداخلة',
    'cash_paid_expenses'    => 'نقد مدفوع للمصروفات',
    'cash_paid_suppliers'   => 'نقد مدفوع للموردين',
    'expenses_and_suppliers'=> 'المصروفات + الموردون',
    'from_customers'        => 'من العملاء',
    'cash_received'         => 'النقد المستلم',
    'cash_from_customers'   => 'نقد مستلم من العملاء',
    'based_on_invoice_date' => 'بناءً على تاريخ الفاتورة',
    'days'                  => 'أيام',
    'month'                 => 'الشهر',
    'totals'                => 'الإجماليات',
    'year_total'            => 'مجموع السنة',
    'invoice_count'         => 'عدد الفواتير',
    'outstanding'           => 'المستحقات',
    'total_collected'       => 'إجمالي المحصل',

    // ── التنقل (مضاف) ──
    'nav_accounting'        => 'المحاسبة',

    // ── التقارير (مضاف) ──
    'delete_invoice_confirm'=> 'حذف هذه الفاتورة واسترجاع المخزون؟',
    'payment_modes'         => 'طرق الدفع',
    'pnl_note'              => 'ملاحظة الأرباح والخسائر',
    'profit_loss'           => 'الأرباح والخسائر',

];
